---
title: "VUW_STAT452_Assn2_Q2"
author: "Quan Zhao"
date: "2024-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/Users/felixzhao/Documents/@Study/STAT\ 452/STAT452/Assignments/2")
```

## Load Data

```{r Ship Damage}
# Read in the ship damage dataset.
damage <- read.csv("Ship Damage.csv", header = TRUE)
# Extract numbers of damage incidents for ships of types A to C.
y.AC <- damage$DAMAGE[damage$TYPE %in% c("A", "B", "C")]
# Extract numbers of damage incidents for ships of types D and E. 
y.DE <- damage$DAMAGE[damage$TYPE %in% c("D", "E")]
```

```{r functions}
calculate_posterior_mean <- function(b, n, prior_mean, sample_mean) {
  return (b/(b+n)) * prior_mean + (n/(b+n)) * sample_mean
}

calculate_95_CI <- function(a, b, sum, n) {
  qgamma(c(0.025, 0.975), a + sum, b + n)
}
```

```{r global variables}
y.AC.mean <- mean(y.AC)
y.AC.n <- length(y.AC)
y.AC.sum <- sum(y.AC)
y.AC.w <- 10
y.AC.prior_mean <- 11

y.DE.mean <- mean(y.DE)
y.DE.n <- length(y.DE)
y.DE.sum <- sum(y.DE)
y.DE.w <- 10
y.DE.prior_mean <- 7
```

```{r Q2a & b}

# AC

y.AC.a <- 55/6
y.AC.b <- 5/6

print(paste("y.AC.a:", round(y.AC.a,4), "y.AC.b:", round(y.AC.b,4)))

## posterior mean of y.AC
print(paste("posterior mean of y.AC:", round(calculate_posterior_mean(y.AC.b, y.AC.n, y.AC.prior_mean, y.AC.w),4)))

## 95% credible intervals for theta AC.
print(paste("95% credible intervals for theta AC:", round(calculate_95_CI(y.AC.a, y.AC.b, y.AC.sum, y.AC.n),4)))

```

```{r}
# Calculate the mean of y.DE
mean_y.DE <- mean(y.DE)

# Calculate the number of observations in y.DE
n_y.DE <- length(y.DE)

# Print the results
print(paste("Mean of y.DE:", mean_y.DE))
print(paste("Number of observations in y.DE:", n_y.DE))

# Calculate the sum of y.DE
sum_y.DE <- sum(y.DE)

# Print the result
print(paste("Sum of y.DE:", sum_y.DE))

a_DE <- 35/4
b_DE <- 5/4
theta_0_DE <- 7
w_DE <- 10

a_DE + sum_y.DE

b_DE + n_y.DE

print(paste("posterior mean of y.DE:", (w_DE/(w_DE+n_y.DE))* theta_0+(n_y.DE/(w_DE+n_y.DE))*mean_y.DE))


# 95% credible intervals for theta DE.

round(qgamma(c(0.025, 0.975), a + sum_y.DE, b + n_y.DE), 4)

```


```{r Q2 C}

q2c.w <- seq(1, 100)

q2c.a <- 15*q2c.w
q2c.b <- q2c.w
q2c.theta_0 <- q2c.a / q2c.b 

q2c.n <- length(y.DE)
q2c.y_mean <- mean(y.DE)



posterior_mean <- calculate_posterior_mean(q2c.b, q2c.n, q2c.theta_0, q2c.y_mean)
print(posterior_mean)

plot(posterior_mean, type = 'o', col = 'blue', xlab = 'Index', ylab = 'Values', main = 'Sequence of Double Numbers')

# Additional point to add
additional_point <- 0.82
index_of_additional_point <- length(posterior_mean) + 1 # Assuming it's the next in sequence

# Add the additional point to the plot
points(index_of_additional_point, additional_point, col = 'red', pch = 19)
```   
